version: '3'
services:
  untisplanner:
    command: sh -c "npm rebuild rollup && npm run dev"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "0.0.0.0:6450:3000"
      - "0.0.0.0:24678:24678"
    volumes:
      - .:/app
    stdin_open: true
