version: '3'
services:
  untisplanner:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - "6500:3000"
       - "24678:24678"
    volumes:
       - .:/app
       - node_modules:/app/node_modules

volumes:
  node_modules: