
ARG NODE_VERSION=18.14.2

FROM node:${NODE_VERSION}-slim as base

ARG PORT=3000

ENV NODE_ENV=production

WORKDIR /app

FROM base as build

COPY --link package.json package-lock.json ./
RUN npm install --production=false

COPY --link . .

RUN npm run build
RUN npm prune

FROM base

ENV PORT=$PORT

COPY --from=build /app/.output /app/.output

CMD [ "node", ".output/server/index.mjs" ]